{% set name = "types-xxhash" %}
{% set version = "2.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-xxhash-{{ version }}.tar.gz
  sha256: e65678b9a9dba1261e8cb97473c9bb16ead38633db9bc4815773866fee4f59fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/xxhash-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for xxhash
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
